url: https://dondokono.github.io
baseurl: /DonDokoWeb/

# Site settings
title: DonDoko Norway
email: dondoko.norway@gmail.com
description: "First and only Taiko group in Norway. Based in Oslo"


# Team names, titles and social links
people:
- name: Masayo
  pic: 1
  position: Group leader and main teacher
   # social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
 #   - title: google-plus
 #     url: #

- name: Nicole
  pic: 2
  position: External contact
  # social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
 #   - title: google-plus
 #     url: #

- name: Siri
  pic: 3
  position: Social media manager and Internal contact
 # social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
 #   - title: google-plus
 #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: twitter
 #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/dondoko.norway/
  - title: instagram
    url: https://www.instagram.com/dondokonorway/
#  - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
 #   url: http://bitbucket.org/jekyll
#  - title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Trondheimsveien 2, H, 
  - line: 0560 Oslo

# Build settings
markdown: kramdown
permalink: pretty
